/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum9;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author huppe
 */
public class AdminPanel extends javax.swing.JFrame {

    private JComboBox<String> statusComboBox;
    private JTable tiketTable;
    private DefaultTableModel tableModel;
    
    public AdminPanel() throws ClassNotFoundException {
        setTitle("Admin Panel - Filter Tiket Laporan");
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        JPanel panel = new JPanel(new BorderLayout());

        String[] statuses = {"Semua", "selesai", "belum selesai"};
        statusComboBox = new JComboBox<>(statuses);
        statusComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    filterData();
                } catch (ClassNotFoundException ex) {
                    ex.printStackTrace();
                }
            }
        });

        panel.add(statusComboBox, BorderLayout.NORTH);

        tableModel = new DefaultTableModel(new String[]{"ID", "Deskripsi", "Status"}, 0);
        tiketTable = new JTable(tableModel);

        panel.add(new JScrollPane(tiketTable), BorderLayout.CENTER);

        add(panel);
        try {
            loadData("");
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        initComponents();
    }
    
    private void loadData(String statusFilter) throws ClassNotFoundException {
        String SUrl = "jdbc:mysql://localhost:3306/java_db";
        String SUser = "root";
        String SPass = "";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(SUrl, SUser, SPass);
            String sql = "SELECT * FROM tiket_laporan";
            if (!statusFilter.equals("")) {
                sql += " WHERE status = ?";
            }
            PreparedStatement stmt = conn.prepareStatement(sql);
            if (!statusFilter.equals("")) {
                stmt.setString(1, statusFilter);
            }
            ResultSet rs = stmt.executeQuery();

            tableModel.setRowCount(0); // Clear table

            while (rs.next()) {
                tableModel.addRow(new Object[]{rs.getInt("id"), rs.getString("deskripsi"), rs.getString("status")});
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void filterData() throws ClassNotFoundException {
        String selectedStatus = statusComboBox.getSelectedItem().toString();
        if (selectedStatus.equals("Semua")) {
            loadData("");
        } else {
            loadData(selectedStatus);
        }
    }
    /**
     * 
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminPanel().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
